version: "3.9"
services:
  analytics_collector:
    container_name: analytics_collector_container
    ports:
      - "8081:8080"
    build: .
    environment:
      - CONFIG_PATH=configs/dev.yaml
    depends_on:
      - postgres
    networks:
      - analysis_collector_network

  postgres:
    container_name: postgres_container
    image: postgres:16.0
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=analysis_db
    restart: unless-stopped
    networks:
      - analysis_collector_network

volumes:
  postgres:

networks:
  analysis_collector_network:
    driver: bridge